src/Destiny/AppBundle/Entity/Usuarios.php
<?php

namespace Destiny\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Symfony\Component\Validator\Constraints as Assert;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * Idiomas
 *
 * @ORM\Table(name="usuario")
 * @ORM\Entity(repositoryClass="Destiny\AppBundle\Entity\Repository\UsuariosRepository")
 * @UniqueEntity("email")
 * @UniqueEntity("username")
 */

class Usuarios extends BaseUser
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;


	/**
	 * @var \DateTime
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(name="fechaCreacion", type="datetime")
	 */
	private $fechaCreacion;

	/**
	 * @var \DateTime
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(name="fechaModificacion", type="datetime")
	 */
	private $fechaModificacion;



    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

	public function getEstado()
	{
		return $this->enabled;
	}

	public function setEstado($estado)
	{
		$this->enabled = $estado;

		return $this;
	}

	public function getSlug()
	{
		return $this->usernameCanonical;
	}

	public function setSlug($usernameCanonical)
	{
		 $this->usernameCanonical = $usernameCanonical;

		return $this;
	}

    /**
     * Set fechaCreacion
     *
     * @param \DateTime $fechaCreacion
     * @return Usuarios
     */
    public function setFechaCreacion($fechaCreacion)
    {
        $this->fechaCreacion = $fechaCreacion;

        return $this;
    }

    /**
     * Get fechaCreacion
     *
     * @return \DateTime 
     */
    public function getFechaCreacion()
    {
        return $this->fechaCreacion;
    }

    /**
     * Set fechaModificacion
     *
     * @param \DateTime $fechaModificacion
     * @return Usuarios
     */
    public function setFechaModificacion($fechaModificacion)
    {
        $this->fechaModificacion = $fechaModificacion;

        return $this;
    }

    /**
     * Get fechaModificacion
     *
     * @return \DateTime 
     */
    public function getFechaModificacion()
    {
        return $this->fechaModificacion;
    }
}

src/Destiny/AppBundle/Form/MensajesType.php
<?php

namespace Destiny\AppBundle\Form;



use Destiny\AppBundle\Entity\Mensajes;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Translation\Translator;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;


/**
 * Class NewsletterType
 * @package Destiny\AppBundle\Form
 *

 */
class MensajesType extends AbstractType
{
	protected $em, $translator;


	public function __construct (EntityManager $em, Translator $translator)
	{
		$this->em = $em;
		$this->translator = $translator;

	}

	/**
	 * @param FormBuilderInterface $builder
	 * @param array                $options
	 */
	public function buildForm (FormBuilderInterface $builder, array $options)
	{
		$builder
			->add ('email', 'email', ['label' => $this->translator->trans ('mensajes.form.email'),
									  'disabled' => true])
		->add ('telefono', 'text', ['label' => $this->translator->trans ('mensajes.form.telephone'),
			'disabled' => true])
		->add ('asunto', 'text', ['label' => $this->translator->trans ('mensajes.form.subject'),
			'disabled' => true])
		->add ('cuerpo', 'textarea', ['label' => $this->translator->trans ('mensajes.form.body'),
			'disabled' => true]);
	}

	/**
	 * @param OptionsResolverInterface $resolver
	 */
	public function setDefaultOptions (OptionsResolverInterface $resolver)
	{
		$resolver->setDefaults (array (
				'data_class' => 'Destiny\AppBundle\Entity\Mensajes'
		));
	}

	/**
	 * @return string
	 */
	public function getName ()
	{
		return 'destiny_appbundle_mensajes';
	}

	public function newEntity ()
	{
		$mensaje = new Mensajes();

		return $mensaje;
	}

	public function preEdit($mensaje)
	{
		$mensaje->setEstado(true);
		$this->em->persist ($mensaje);
		$this->em->flush ();

		return $mensaje;
	}

	public function isDeletable ($mensaje)
	{

		return TRUE;
	}

	public function isChangeable ($mensaje)
	{

		return TRUE;
	}

	public function listElements ()
	{
		return
			[
				$this->translator->trans ('mensajes.list.subject') => 'asunto'
			];

	}

	public function getMensajesSinLeer()
	{
		 return $this->em->getRepository('DestinyAppBundle:Mensajes')->getMensajesSinLeer();
	}

	public function cantCreate ($mensaje)
	{

		return TRUE;
	}


}

src/Destiny/AppBundle/Resources/views/backendBase.html.twig
{% extends "::base.html.twig" %}

{% block stylesheets %}
    <link href="{{ asset('asset/backend/css/AdminLTE.min.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/backend/css/skin-blue.min.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/common/css/modal.css') }}" rel="stylesheet">
	<!-- Font Awesome Icons -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<!-- Ionicons -->
	<link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block title %}{{ 'dashboard.project' | trans }}{% endblock %}
{% block bodyclass %}skin-blue{% endblock %}
{% block body %}
	<div class="wrapper">

		<!-- Main Header -->
		<header class="main-header">

			<!-- Logo -->
			<a href="{{ path('portadaBackend') }}" class="logo">{{ 'dashboard.project' | trans }}</a>

			<!-- Header Navbar -->
			<nav class="navbar navbar-static-top" role="navigation">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a>
				<!-- Navbar Right Menu -->
				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav">
						<!-- Messages: style can be found in dropdown.less-->
						<li class="dropdown messages-menu">
							<!-- Menu toggle button -->
							{% set mensajes = mensajes.mensajesSinLeer %}
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-envelope-o"></i>
								{{ 'mensajes.list.title' | trans }}
								{% if  mensajes | length > 0 %}
								<span class="label label-success">{{ mensajes | length }}</span>
								{% endif %}
							</a>
							<ul class="dropdown-menu">
								<li class="header">
									{% if  mensajes | length > 0 %}
										{{ 'mensajes.list.cant' | trans({'%cantidad%': mensajes | length }) }}
									{% else %}
										{{ 'mensajes.list.noread' | trans () }}
									{% endif %}
								</li>
								<li>
									<!-- inner menu: contains the messages -->
									<ul class="menu">
										{%  for mensaje in mensajes %}
										<li><!-- start message -->
											<a href="#">
												<!-- Message title and timestamp -->

													<a href="{{ path('editBackend',{'entity':'mensajes','element':mensaje.slug }) }}">
														{{ mensaje.asunto }}

													<small><i class="fa fa-clock-o"></i> {{ mensaje.fechaCreacion | date ('d/m/Y H:i') }}</small>
											</a>
												<!-- The message -->
											</a>
										</li><!-- end message -->
										{% endfor %}
									</ul><!-- /.menu -->
								</li>
								<li class="footer">
									<a href="{{ path('listBackend',{'entity':'mensajes'}) }}">
										{{ 'mensajes.list.all' | trans  }}
									</a>
								</li>
							</ul>
						</li><!-- /.messages-menu -->
						<li class="dropdown messages-menu">
							<!-- Menu toggle button -->

							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-database"></i>
								{{ 'configuration.list.title' | trans }}
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="{{ path('listBackend',{'entity':'idiomas'}) }}">
										<i class="fa fa-flag-o"></i>
										{{ 'configuration.list.language' | trans }}
									</a>
								</li>
								<li>
									<a href="{{ path('listBackend',{'entity':'empresaRedesSociales'}) }}">
										<i class="fa fa-globe"></i>{{ 'configuration.list.redesSociales' | trans }}
									</a>
								</li>
								<li>
									<a href="{{ path('editBackend',{'entity':'empresaContacto','element':'default'}) }}">
										<i class="fa fa-building"></i>{{ 'configuration.list.contacto' | trans }}
									</a>
								</li>
								<li>
									<a href="{{ path('editBackend',{'entity':'empresaWeb','element':'default'}) }}">
										<i class="fa fa-cloud"></i>{{ 'configuration.list.web' | trans }}
									</a>
								</li>
							</ul>
						</li><!-- /.messages-menu -->
					</ul>
				</div>
			</nav>
		</header>
		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<div class="user-panel">
					<div class="pull-left info">
						<p>
							<a href="{{ path('portadaBackend') }}">
							<img class="img-circle img-responsive"  width="160px" src="{{ asset (empresa.web.webpath) }}">
						</a></p>
						<p>{{ 'dashboard.saludo' | trans }} {{ app.user | capitalize }}</p>
						<!-- Status -->
						<i class="fa fa-circle text-success"></i> {{ 'dashboard.status' | trans }}
						<a href="{{ path('fos_user_security_logout') }}">({{ 'dashboard.logout' | trans  }})</a>
						<a href="{{ path('portadaWeb') }}"><i class="fa fa-globe"></i> {{ 'dashboard.gotfront' | trans }}</a>
					</div>
				</div>

				<!-- Sidebar Menu -->
				<ul class="sidebar-menu">
					<!-- Optionally, you can add icons to the links -->
					<li class="treeview">
						<a href="#">
							<i class="fa fa-bars"></i>
							<span>{{ 'configuration.list.content' | trans }}</span>
							<i class="fa fa-angle-left pull-right"></i>
						</a>
						<ul class="treeview-menu">
							<li>
								<a href="#">
									<i class="fa fa-list-alt"></i>
									{{ 'configuration.list.menus' | trans }}
								</a>
							</li>
							<li>
								<a href="#">
									<i class="fa fa-file-text"></i>
									{{ 'configuration.list.sections' | trans }}
								</a>
							</li>
						</ul>
					</li>
					<li class="treeview">
						<a href="#">
							<i class="fa fa-bars"></i>
							<span>{{ 'configuration.list.contentMedia' | trans }}</span>
							<i class="fa fa-angle-left pull-right"></i>
						</a>
						<ul class="treeview-menu">
							<li>
								<a href="{{ path('listBackend',{'entity':'adjuntos'}) }}">
									<i class="fa fa-file-pdf-o"></i>
									{{ 'configuration.list.pdf' | trans }}
									</a>
									</li>
							<li>
								<a href="{{ path('listBackend',{'entity':'videos'}) }}">
									<i class="fa fa-youtube"></i>
									{{ 'configuration.list.videos' | trans }}
								</a>
							</li>
							<li>
								<a href="{{ path('listBackend',{'entity':'imagenes'}) }}">
									<i class="fa fa-file-image-o"></i>
									{{ 'configuration.list.images' | trans }}
								</a>
							</li>
							<li>
								<a href="#">
									<i class="fa fa-slideshare"></i>
									{{ 'configuration.list.slider' | trans }}
								</a>
							</li>

						</ul>
					</li>
					<li>
						<a href="{{ path('listBackend',{'entity':'usuarios'}) }}">
							<i class="fa fa-users"></i>
							<span>{{ 'configuration.list.users' | trans }}</span>
						</a>
					</li>
					<li>
						<a href="{{ path('listBackend',{'entity':'newsletter'}) }}">
							<i class="fa fa-newspaper-o"></i>
							<span>{{ 'configuration.list.newsletter' | trans }}</span>
						</a>
					</li>

				</ul><!-- /.sidebar-menu -->
			</section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<section class="content-header">
				<h1>
					{% block titleBackend %}
						{%  set actual = entity~'.list.title' %}
						{{ actual | trans }}
					{% if (cantCreate == false) and (app.request.attributes.get('_route') != 'portadaBackend') %}
					{% set newEntity = entity ~'.list.new' %}
					<a class="btn btn-success pull-right" href="{{ path('createBackend',{'entity':entity}) }}">
						<i class="fa fa-plus-circle"></i>

						{{ newEntity | trans }}
						</a>
					{% endif %}
					{% endblock %}
				</h1>
			</section>

			<!-- Main content -->
			<section class="content">
			<div class="row">
				<div class="col-md-12 alerta">
					{% for type, flashMessage in app.session.flashbag.all() %}
						<div class="alert alert-{{ type }} fade in">
							<a data-dismiss="alert" class="pull-right" href="" type="button">
								<i class="fa fa-times"></i>
							</a>
							{% if flashMessage.title is defined %}
								<strong>{{ flashMessage.title }}</strong><br>
								{{ flashMessage.message }}
							{% endif %}
						</div>
					{% endfor %}
				</div>
				{% block backendBody %}

				{% endblock %}
				<!-- Your Page Content Here -->
				</div>
			</section><!-- /.content -->
		</div><!-- /.content-wrapper -->

		<!-- Main Footer -->
		<footer class="main-footer">
			<!-- To the right -->
			<!-- Default to the left -->
			<strong>Copyright &copy; 2015 <a href="#">{{ 'dashboard.name' | trans }}</a>.</strong>
		</footer>

	</div><!-- ./wrapper -->
{% endblock %}
{% block javascripts %}
	<script src="{{ asset('asset/backend/js/app.min.js') }}"></script>
{% endblock %}

src/Destiny/AppBundle/Resources/views/instalacionBase.html.twig
{% extends "::base.html.twig" %}

{% block stylesheets %}
	<link href="{{ asset('asset/backend/css/dashboard.css') }}" rel="stylesheet">
	<link href="{{ asset('asset/common/css/modal.css') }}" rel="stylesheet">
{% endblock %}
{% block title %}Destiny Dashboard{% endblock %}

{% block body %}
	<div class="col-md-12 main">
		
		<h1 class="page-header">{% block backendTitle %}{% endblock %}</h1>

		<div class="col-md-12 alerta">
			{% for type, flashMessage in app.session.flashbag.all() %}
				<div class="alert alert-{{ type }} fade in">
					<a data-dismiss="alert" class="pull-right" href="" type="button">
						<i class="fa fa-times"></i>
					</a>
					{% if flashMessage.title is defined %}
						<strong>{{ flashMessage.title }}</strong><br>
						{{ flashMessage.message }}
					{% endif %}
				</div>
			{% endfor %}
		</div>


		{% block  backendBody %}
		{% endblock %}

	</div>

{% endblock %}