src/Destiny/AppBundle/Entity/EmpresaContacto.php
<?php

namespace Destiny\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * EmpresaContacto
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Destiny\AppBundle\Entity\Repository\EmpresaContactoRepository")
 * @UniqueEntity("nombre")
 */
class EmpresaContacto
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="nombre", type="string", length=255)
	 * @Assert\NotBlank(message="contacto.name.notblank")
	 * @Assert\Length(
	 *      min = 2,
	 *      max = 10,
	 *      minMessage = "contacto.name.min",
	 *      maxMessage = "contacto.name.max"
	 * )
	 *
	 */
	private $nombre;

	/**
	 * @var string
	 * @Gedmo\Slug(fields={"nombre"})
	 * @ORM\Column(name="slug", type="string", length=255)
	 */
	private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="direccion", type="string", length=255)
     * @Assert\NotBlank(message="contacto.direccion.notblank")
     * @Assert\Length(
     *      min = 2,
     *      minMessage = "contacto.direccion.min",
     * )
     *
     */
    private $direccion;

    /**
     * @var string
     *
     * @ORM\Column(name="ciudad", type="string", length=255)
     * @Assert\NotBlank(message="contacto.ciudad.notblank")
     * @Assert\Length(
     *      min = 2,
     *      minMessage = "contacto.ciudad.min",
     * )
     */
    private $ciudad;

    /**
     * @var string
     *
     * @ORM\Column(name="provincia", type="string", length=255)
     * @Assert\NotBlank(message="contacto.provincia.notblank")
     * @Assert\Length(
     *      min = 2,
     *      minMessage = "contacto.provincia.min",
     * )
     */
    private $provincia;

    /**
     * @var string
     *
     * @ORM\Column(name="pais", type="string", length=255)
     * @Assert\NotBlank(message="contacto.pais.notblank")
     * @Assert\Length(
     *      min = 2,
     *      minMessage = "contacto.pais.min",
     * )
     */
    private $pais;

    /**
     * @var string
     *
     * @ORM\Column(name="telefono", type="integer")
     * @Assert\Type(type="integer", message="contacto.numero")
     */
    private $telefono;

    /**
     * @var integer
     *
     * @ORM\Column(name="movil", type="integer")
     * @Assert\Type(type="integer", message="contacto.numero")
     */
    private $movil;

    /**
     * @var integer
     *
     * @ORM\Column(name="fax", type="integer")
     * @Assert\Type(type="integer", message="contacto.numero")
     */
    private $fax;

	/**
	 * @var \DateTime
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(name="fechaCreacion", type="datetime")
	 */
	private $fechaCreacion;

	/**
	 * @var \DateTime
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(name="fechaModificacion", type="datetime")
	 */
	private $fechaModificacion;

	/**
	 * @var boolean
	 *
	 * @ORM\Column(name="estado", type="boolean")
	 */
	private $estado;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

	public function __toString()
	{
		return $this->getNombre();
	}

	public function getDireccionCompleta()
	{
		return $this->getDireccion() .', ' .
			$this->getCiudad() .'( ' .$this->getProvincia() .',' .$this->getPais() .')';
	}
    /**
     * Set nombre
     *
     * @param string $nombre
     * @return EmpresaContacto
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return EmpresaContacto
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set direccion
     *
     * @param string $direccion
     * @return EmpresaContacto
     */
    public function setDireccion($direccion)
    {
        $this->direccion = $direccion;

        return $this;
    }

    /**
     * Get direccion
     *
     * @return string 
     */
    public function getDireccion()
    {
        return $this->direccion;
    }

    /**
     * Set ciudad
     *
     * @param string $ciudad
     * @return EmpresaContacto
     */
    public function setCiudad($ciudad)
    {
        $this->ciudad = $ciudad;

        return $this;
    }

    /**
     * Get ciudad
     *
     * @return string 
     */
    public function getCiudad()
    {
        return $this->ciudad;
    }

    /**
     * Set provincia
     *
     * @param string $provincia
     * @return EmpresaContacto
     */
    public function setProvincia($provincia)
    {
        $this->provincia = $provincia;

        return $this;
    }

    /**
     * Get provincia
     *
     * @return string 
     */
    public function getProvincia()
    {
        return $this->provincia;
    }

    /**
     * Set pais
     *
     * @param string $pais
     * @return EmpresaContacto
     */
    public function setPais($pais)
    {
        $this->pais = $pais;

        return $this;
    }

    /**
     * Get pais
     *
     * @return string 
     */
    public function getPais()
    {
        return $this->pais;
    }

    /**
     * Set telefono
     *
     * @param string $telefono
     * @return EmpresaContacto
     */
    public function setTelefono($telefono)
    {
        $this->telefono = $telefono;

        return $this;
    }

    /**
     * Get telefono
     *
     * @return string 
     */
    public function getTelefono()
    {
        return $this->telefono;
    }

    /**
     * Set movil
     *
     * @param integer $movil
     * @return EmpresaContacto
     */
    public function setMovil($movil)
    {
        $this->movil = $movil;

        return $this;
    }

    /**
     * Get movil
     *
     * @return integer 
     */
    public function getMovil()
    {
        return $this->movil;
    }

    /**
     * Set fax
     *
     * @param integer $fax
     * @return EmpresaContacto
     */
    public function setFax($fax)
    {
        $this->fax = $fax;

        return $this;
    }

    /**
     * Get fax
     *
     * @return integer 
     */
    public function getFax()
    {
        return $this->fax;
    }

    /**
     * Set fechaCreacion
     *
     * @param \DateTime $fechaCreacion
     * @return EmpresaContacto
     */
    public function setFechaCreacion($fechaCreacion)
    {
        $this->fechaCreacion = $fechaCreacion;

        return $this;
    }

    /**
     * Get fechaCreacion
     *
     * @return \DateTime 
     */
    public function getFechaCreacion()
    {
        return $this->fechaCreacion;
    }

    /**
     * Set fechaModificacion
     *
     * @param \DateTime $fechaModificacion
     * @return EmpresaContacto
     */
    public function setFechaModificacion($fechaModificacion)
    {
        $this->fechaModificacion = $fechaModificacion;

        return $this;
    }

    /**
     * Get fechaModificacion
     *
     * @return \DateTime 
     */
    public function getFechaModificacion()
    {
        return $this->fechaModificacion;
    }

    /**
     * Set estado
     *
     * @param boolean $estado
     * @return EmpresaContacto
     */
    public function setEstado($estado)
    {
        $this->estado = $estado;

        return $this;
    }

    /**
     * Get estado
     *
     * @return boolean 
     */
    public function getEstado()
    {
        return $this->estado;
    }
}

src/Destiny/AppBundle/Entity/Idiomas.php
<?php

namespace Destiny\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Idiomas
 *
 * @ORM\Table(name="idiomas")
 * @ORM\Entity(repositoryClass="Destiny\AppBundle\Entity\Repository\IdiomasRepository")
 * @UniqueEntity("nombre")
 * @UniqueEntity("isoCode")
 */
class Idiomas
{
	/**
	 * @var integer
	 *
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="nombre", type="string", length=255)
	 * @Assert\NotBlank(message="language.name.notblank")
	 * @Assert\Length(
	 *      min = 2,
	 *      max = 50,
	 *      minMessage = "language.name.min",
	 *      maxMessage = "language.name.max"
	 * )
	 *
	 * @Assert\Regex(
	 *     pattern="/\d/",
	 *     match=false,
	 *     message="language.name.notnumber"
	 * )
	 */
	private $nombre;

	/**
	 * @var string
	 * @Gedmo\Slug(fields={"isoCode"})
	 * @ORM\Column(name="slug", type="string", length=255)
	 */
	private $slug;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="isoCode", type="string", length=255)
	 * 	 * @Assert\NotBlank(message="language.isocode.notblank")
	 * @Assert\Length(
	 *      min = 2,
	 *      max = 5,
	 *      minMessage = "language.isocode.min",
	 *      maxMessage = "language.isocode.max"
	 * )
	 *
	 * @Assert\Regex(
	 *     pattern="/\d/",
	 *     match=false,
	 *     message="language.isocode.notnumber"
	 * )
	 */
	private $isoCode;

	/**
	 * @return string
	 * @Assert\File(maxSize="1M",maxSizeMessage="language.flag.maxSize")
	 * @Assert\Image(mimeTypesMessage="language.flag.notimage")
	 *
	 */
	private $archivo;

	/**
	 * @ORM\Column(name="ruta", type="string")
	 */
	private $ruta;


	/**
	 * @var string
	 *
	 * @ORM\Column(name="estado", type="boolean")
	 */
	private $estado;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="defecto", type="boolean")
	 */
	private $defecto;

	/**
	 * @var \DateTime
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(name="fechaCreacion", type="datetime")
	 */
	private $fechaCreacion;

	/**
	 * @var \DateTime
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(name="fechaModificacion", type="datetime")
	 */
	private $fechaModificacion;


	public function __toString()
	{
		return $this->getNombre();
	}

	public function getAbsolutePath()
	{
		return null === $this->ruta
			? null
			: $this->getUploadRootDir().'/'.$this->ruta;
	}

	public function getWebPath()
	{
		return null === $this->ruta
			? null
			: $this->getUploadDir().'/'.$this->ruta;
	}

	protected function getUploadRootDir()
	{
		// la ruta absoluta del directorio donde se deben
		// guardar los archivos cargados
		return __DIR__.'/../../../../web/'.$this->getUploadDir();
	}

	protected function getUploadDir()
	{
		// se deshace del __DIR__ para no meter la pata
		// al mostrar el documento/imagen cargada en la vista.
		return 'asset/common/img/lang';
	}

	public function upload()
	{
		// the file property can be empty if the field is not required
		if (null === $this->getArchivo()) {
			return;
		}


		// aquí usa el nombre de archivo original pero lo debes
		// sanear al menos para evitar cualquier problema de seguridad

		// move takes the target directory and then the
		// target filename to move to
		$nombreArchivo = $this->getIsoCode().'.' .$this->getArchivo()->getClientOriginalExtension();



		$this->getArchivo()->move(
			$this->getUploadRootDir(),
			$nombreArchivo
		);

		// set the path property to the filename where you've saved the file
		$this->ruta = $nombreArchivo;

		// limpia la propiedad «file» ya que no la necesitas más
		$this->archivo = null;
	}

	public function getType()
	{
		return 'image';
	}

	public function setArchivo(UploadedFile $archivo)
	{
		$this->archivo = $archivo;

		return $this;
	}

	public function getArchivo()
	{
		return $this->archivo;

	}

	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set nombre
	 *
	 * @param string $nombre
	 * @return Idiomas
	 */
	public function setNombre($nombre)
	{
		$this->nombre = $nombre;

		return $this;
	}

	/**
	 * Get nombre
	 *
	 * @return string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Set slug
	 *
	 * @param string $slug
	 * @return Idiomas
	 */
	public function setSlug($slug)
	{
		$this->slug = $slug;

		return $this;
	}

	/**
	 * Get slug
	 *
	 * @return string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Set isoCode
	 *
	 * @param string $isoCode
	 * @return Idiomas
	 */
	public function setIsoCode($isoCode)
	{
		$this->isoCode = $isoCode;

		return $this;
	}

	/**
	 * Get isoCode
	 *
	 * @return string
	 */
	public function getIsoCode()
	{
		return $this->isoCode;
	}

	/**
	 * Set altImagen
	 *
	 * @param string $altImagen
	 * @return Idiomas
	 */
	public function setAltImagen($altImagen)
	{
		$this->altImagen = $altImagen;

		return $this;
	}

	/**
	 * Get altImagen
	 *
	 * @return string
	 */
	public function getAltImagen()
	{
		return $this->altImagen;
	}

	/**
	 * Set nombreImagen
	 *
	 * @param string $nombreImagen
	 * @return Idiomas
	 */
	public function setNombreImagen($nombreImagen)
	{
		$this->nombreImagen = $nombreImagen;

		return $this;
	}

	/**
	 * Get nombreImagen
	 *
	 * @return string
	 */
	public function getNombreImagen()
	{
		return $this->nombreImagen;
	}

	/**
	 * Set tituloImagen
	 *
	 * @param string $tituloImagen
	 * @return Idiomas
	 */
	public function setTituloImagen($tituloImagen)
	{
		$this->tituloImagen = $tituloImagen;

		return $this;
	}

	/**
	 * Get tituloImagen
	 *
	 * @return string
	 */
	public function getTituloImagen()
	{
		return $this->tituloImagen;
	}

	/**
	 * Set ruta
	 *
	 * @param string $ruta
	 * @return Idiomas
	 */
	public function setRuta($ruta)
	{
		$this->ruta = $ruta;

		return $this;
	}

	/**
	 * Get ruta
	 *
	 * @return string
	 */
	public function getRuta()
	{
		return $this->ruta;
	}

	/**
	 * Set estado
	 *
	 * @param boolean $estado
	 * @return Idiomas
	 */
	public function setEstado($estado)
	{
		$this->estado = $estado;

		return $this;
	}

	/**
	 * Get estado
	 *
	 * @return boolean
	 */
	public function getEstado()
	{
		return $this->estado;
	}

	/**
	 * Set defecto
	 *
	 * @param boolean $defecto
	 * @return Idiomas
	 */
	public function setDefecto($defecto)
	{
		$this->defecto = $defecto;

		return $this;
	}

	/**
	 * Get defecto
	 *
	 * @return boolean
	 */
	public function getDefecto()
	{
		return $this->defecto;
	}

	/**
	 * Set fechaCreacion
	 *
	 * @param \DateTime $fechaCreacion
	 * @return Idiomas
	 */
	public function setFechaCreacion($fechaCreacion)
	{
		$this->fechaCreacion = $fechaCreacion;

		return $this;
	}

	/**
	 * Get fechaCreacion
	 *
	 * @return \DateTime
	 */
	public function getFechaCreacion()
	{
		return $this->fechaCreacion;
	}

	/**
	 * Set fechaModificacion
	 *
	 * @param \DateTime $fechaModificacion
	 * @return Idiomas
	 */
	public function setFechaModificacion($fechaModificacion)
	{
		$this->fechaModificacion = $fechaModificacion;

		return $this;
	}

	/**
	 * Get fechaModificacion
	 *
	 * @return \DateTime
	 */
	public function getFechaModificacion()
	{
		return $this->fechaModificacion;
	}
}

src/Destiny/AppBundle/Resources/views/Instalaccion/crearUsuarioAdmin.html.twig
{% extends "DestinyAppBundle::instalacionBase.html.twig" %}

{% block backendTitle %}{{ 'instalacion.usuario.titulo' | trans }}{% endblock %}

{% block backendBody %}

	<h2>{{ 'instalacion.usuario.info' | trans }}</h2>
	<div class="progress">
		<div class="progress-bar progress-bar-striped active" role="progressbar"
		     aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
			<span class="sr-only">100% Complete</span>
		</div>
	</div>
	{% include 'DestinyAppBundle:Instalaccion:form.html.twig' %}
	<div class="col-md-6">
		<ul>
			<li>{{ 'empresa.form.nombre' | trans }}: {{ empresa }}</li>
			<li>{{ 'empresa.form.slogan' | trans }}: {{ empresa.slogan }}</li>
			<li>{{ 'empresaContacto.form.direccion' }}: {{ contacto.direccionCompleta }} </li>
			<li>{{ 'empresa.form.archivo' | trans }}: <img src="{{ asset( empresa.webPath ) }}" width="20%"></li>
			{% for red in redes %}
				<li><a href="{{ red.url }}">{{ red | raw }}</a> </li>
			{% endfor %}
			<li>{{ 'idiomas.list.name' | trans }}:<img src="{{ asset(idioma.webPath) }}"> </li>
		</ul>
	</div>
{% endblock %}

src/Destiny/AppBundle/Resources/views/Instalaccion/datosEmpresa.html.twig
{% extends "DestinyAppBundle::instalacionBase.html.twig" %}

{% block backendTitle %}{{ 'instalacion.datosEmpresa.titulo' | trans }}{% endblock %}


{% block backendBody %}

	<h2>{{ 'instalacion.datosEmpresa.info' | trans }}</h2>
	<div class="progress">
		<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
			<span class="sr-only">0% Complete</span>
		</div>
	</div>
	{% include 'DestinyAppBundle:Instalaccion:form.html.twig' %}
{% endblock %}

src/Destiny/AppBundle/Resources/views/Instalaccion/datosEmpresaContacto.html.twig
{% extends "DestinyAppBundle::instalacionBase.html.twig" %}

{% block backendTitle %}{{ 'instalacion.datosContacto.titulo' | trans }}{% endblock %}

{% block backendBody %}

	<h2>{{ 'instalacion.datosContacto.info' | trans }}</h2>
	<div class="progress">
		<div class="progress-bar progress-bar-striped active" role="progressbar"
		     aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 25%">
			<span class="sr-only">25% Complete</span>
		</div>
	</div>
{% include 'DestinyAppBundle:Instalaccion:form.html.twig' %}
	<div class="col-md-6">
		<ul>
			<li>{{ 'empresa.form.nombre' | trans }}: {{ empresa }}</li>
			<li>{{ 'empresa.form.slogan' | trans }}: {{ empresa.slogan }}</li>

			<li>{{ 'empresa.form.archivo' | trans }}: <img src="{{ asset( empresa.webPath ) }}" width="20%"></li>
		</ul>
	</div>
{% endblock %}

src/Destiny/AppBundle/Resources/views/Instalaccion/datosEmpresaRedesSocial.html.twig
{% extends "DestinyAppBundle::instalacionBase.html.twig" %}

{% block backendTitle %}{{ 'instalacion.datosRedesSociales.titulo' | trans }}{% endblock %}

{% block backendBody %}

	<h2>{{ 'instalacion.datosRedesSociales.info' | trans }}</h2>
	<div class="progress">
		<div class="progress-bar progress-bar-striped active" role="progressbar"
		     aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
			<span class="sr-only">50% Complete</span>
		</div>
	</div>
	{% include 'DestinyAppBundle:Instalaccion:form.html.twig' %}
	<div class="col-md-6">
		<ul>
			<li>{{ 'empresa.form.nombre' | trans }}: {{ empresa }}</li>
			<li>{{ 'empresa.form.slogan' | trans }}: {{ empresa.slogan }}</li>
			<li>{{ 'empresaContacto.form.direccion' }}: {{ contacto.direccionCompleta }} </li>
			<li>{{ 'empresa.form.archivo' | trans }}: <img src="{{ asset( empresa.webPath ) }}" width="20%"></li>
			{% for red in redes %}
			<li><a href="{{ red.url }}">{{ red | raw }}</a> </li>
			{% endfor %}
		</ul>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12">
	<a href="{{ path('empresaIdiomaDefecto',{'empresa':empresa.slug,'contacto':contacto.slug}) }}"
	   class="btn btn-success pull-right">Continuar <i class="fa fa-arrow-right"></i></a>
	</div>
{% endblock %}

src/Destiny/AppBundle/Resources/views/Instalaccion/form.html.twig
{{ form_start(form, {'method': 'GET'}) }}

	{% for field in form.children if field.vars.name != '_token' %}
		<div class="form-group {% if not field.vars.valid %}has-error{% endif %}">
			{% set field_label = entity_fields[field.vars.name]['label']|default(null) %}
			{{ form_label(field, field_label|trans, { label_attr: { class: 'col-sm-12 control-label' } }) }}
			<div class="col-sm-12">
				{{ form_widget (field,{'attr':{'class':'form-control'}}) }}
				{% if form_errors(field)  != '' %}
					<br>
					<div class="alert alert-danger fade in">
						<a data-dismiss="alert" class="pull-right" href="" type="button">
							<i class="fa fa-times"></i>
						</a>
						<strong>Error</strong><br>
						{{ form_errors(field) }}

					</div>

				{% endif %}
			</div>
		</div>
	{% endfor %}

	<button type="submit" class="btn btn-success pull-right" value="Submit">{{ 'form.save' | trans }}</button>
{{ form_end(form) }}

src/Destiny/AppBundle/Resources/views/Instalaccion/idiomaDefecto.html.twig
{% extends "DestinyAppBundle::instalacionBase.html.twig" %}

{% block backendTitle %}{{ 'instalacion.idioma.titulo' | trans }}{% endblock %}

{% block backendBody %}

	<h2>{{ 'instalacion.idioma.info' | trans }}</h2>
	<div class="progress">
		<div class="progress-bar progress-bar-striped active" role="progressbar"
		     aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 75%">
			<span class="sr-only">75% Complete</span>
		</div>
	</div>
	{% include 'DestinyAppBundle:Instalaccion:form.html.twig' %}
	<div class="col-md-6">
		<ul>
			<li>{{ 'empresa.form.nombre' | trans }}: {{ empresa }}</li>
			<li>{{ 'empresa.form.slogan' | trans }}: {{ empresa.slogan }}</li>
			<li>{{ 'empresaContacto.form.direccion' }}: {{ contacto.direccionCompleta }} </li>
			<li>{{ 'empresa.form.archivo' | trans }}: <img src="{{ asset( empresa.webPath ) }}" width="20%"></li>
			{% for red in redes %}
				<li><a href="{{ red.url }}">{{ red | raw }}</a> </li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}